var product =[{
    "id": 0,
    "name": "",
    "about": "",
    "rating": "",
    "placements": "",
    "courses": "",  
    "exam": "",
    "image": "images/noimage.png",
}, {
    "id": 1,
    "name": "Shri Vaishnav Vidyapeeth Vishwavidyalaya (SVVV), Indore",
    "about": "Shri Vaishnav Vidyapeeth Vishwavidyalaya (SVVV), Indore is recognized as the Most Innovative Private University in MP by Times Icons of Madhya Pradesh 2020 and awarded “Longest Continuous SBC” under CSI Academic Award in CSI-2020 Annual Conventional SVVV Indore offers degree and doctoral courses in the discipline of Engineering, Management, Science, Arts, Design and many more.",
    "rating": "7.2/10",
    "placements": "8/10",
    "courses": " BBA , BBA + MBA , B.Tech , Ph.D , M.Sc , B.Com + M.Com , B.Des + M.Des" ,
    "exam": "JEE Main , SVET",
    "image": "https://www.highereducationdigest.com/wp-content/uploads/2022/05/1-8-550x330.jpg",
}, {
    "id": 2,
    "name": "Institute of Engineering and Science IPS Academy",
    "about": "Indore Professional Studies Academy (IPSA) is one of the Central India's largest educational hub-premises. The academy is affiliated to Devi Ahilya University, Indore, Rajiv Gandhi Technical University, Bhopal, Makhanlal Chaturvedi Rastriya Patrakarita University, Bhopal, Raja Mansingh Tomar Music and Arts University, Gwalior.",
    "rating": "7.2/10",
    "placements": "7.4/10",
    "courses": "BBA , BBA + MBA , B.Tech , Ph.D , M.Sc , B.Com + M.Com",
    "exam": "JEE Main",
    "image": "https://www.ipsacademy.org/assets/uploads/colleges/college_1595577296.jpg",
}, {
    "id": 3,
    "name": "Prestige Institute of Management and Research",
    "about": "Prestige is one of the best institutes offering management education.  The college is popular for its MBA program (both full-time and part-time) with placements ranging between 3-4 LPA with most of the students recruited in BFSI and FMCG sectors. Other than this, the college offers BBA, B.Com, BJMC, LLB, LLM, etc. Admission to all courses is either merit-based or entrance-based. Prestige Institute of Management and Research.",
    "rating": "8/10",
    "placements": "8/10",
    "courses":"BBA , MBA , BCA , B.com{hons} , BA , B.Com + L.L.B {Hons.} , Diploma",
    "exam": "MP BE , JEE Main",
    "image": "https://www.collegebatch.com/static/clg-gallery/prestige-institute-of-management-research-indore-204934.jpg",
}, {
    "id": 4,
    "name": "SAGE University Indore",
    "about": "SAGE University, Indore is a top-tier private university in India which is ranked 4th in Central India, 65th in India by The Times of India 2020 Ranking. It is the number 1 emerging university by Outlook 2020. SAGE University has received approval from the UGC, AICTE, BCI, COA and PCI. The university offers a wide range of courses at UG, PG and PhD level in almost all disciplines such as Engineering, Commerce, Management, Pharmacy, Science, Humanities, Design etc. Some of its top courses are BTech, MBA, BBA, BDes, PhD etc.",
    "rating": "7.9/10",
    "placements": "7.5/10",
    "courses": "BBA , MBA , B.Tech , B.sc , B.com{Hons.} , B.Des + M.C.A",
    "exam": "JEE Main , SEE ",
    "image": "https://images.bhaskarassets.com/web2images/web-frontend/institute/sageUniversity/sageBhopal/sageUniBanner.jpeg",
}, {
    "id": 5,
    "name": "Acropolis Institute Of Technology & Research - [AITR], Indore",
    "about": "Acropolis Institute of Technology and Research (AITR) was established in 2005 by Teach for India Education & Research Samiti. The institute is located in Indore, Madhya Pradesh and ranked as Top Engineering College in Indore by Career 360 and DATA QUEST. The institute has a highly qualified faculty as well as state of the art infrastructure that aids the process of education for students. The deserving students can even avail of among scholarship programs offered by the institute.",
    "rating": "7.8/10",
    "placements": "8.1/10",
    "courses": "B.Tech , M.C.A , MBA , BCA+MCA , Poletechnic , B.Tech {Lateral}, M.Tech",
    "exam": "MP BE , JEE Main",
    "image": "https://aimsr.ac.in/wp-content/uploads/2015/09/building-big-picture.jpg",
}, {
    "id": 6,
    "name": "Medicaps University, Indore",
    "about": "Medi-Caps University ranked 32nd Placements in All India by i3RC Times Engineering Survey 2021. Ranked 1st in M.P. and 41 in India by i3RC Times Engineering Survey 2018. It is the only private university of M.P. that ranked under 150 in India by MHRD NIRF ranking 2017. The university has a 94% placement record and more than 300+ companies have visited for on-campus recruitment. Medi-caps University Indore offers 50+ UG, PG and Doctoral degree programs in the discipline of Engineering, Computer Science, Management, Pharmacy, Agriculture, etc.",
    "rating": "7.4/10",
    "placements": "7.5/10",
    "courses": "B.Tech , MBA , BBA , M.C.A , B.Com{Hons} , B.Sc{Hons} , BCA ",  
    "exam": "JEE Main , MU-SAT",
    "image": "https://upload.wikimedia.org/wikipedia/commons/3/3c/Main_block1.jpg",
},{
    "id": 7,
    "name": "Devi Ahilya Vishwavidyalaya, Indore",
    "about": "DAVV is one of the prime Central Universities in India. The university houses 30 teaching departments and has more than 264 affiliated colleges. DAVV offers admission to more than 2.6 lakh students in over 200 courses at the UG, PG, and Doctorate level every year. The university also offers distance learning courses via the Directorate Of Distance Education. Check DAVV Distance Education",
    "rating": "7.4/10",
    "placements": "6.7/10",
    "courses": "B.E , MBA , B.Ed , M.C.A , BCA , BA , B.P.Ed , BBA+MBA",  
    "exam": "MP BE , JEE Main",
    "image": "https://th.bing.com/th/id/R.e79b7de5dab7ae7296e67edc2acb8320?rik=ljUb1vy3JpbckA&riu=http%3a%2f%2fwww.sports.dauniv.ac.in%2fimages%2f4.jpg&ehk=hDtFnIbBj4LxxnHNKxQVYzZNxFYyafpXrXlV7i94n5Q%3d&risl=&pid=ImgRaw&r=0",
},{
    "id": 8,
    "name": "Oriental University - [OU], Indore",
    "about": "Oriental University, established in 2011 under Oriental Group, is the first self-financed private university in Indore. The university is approved by PCI, BCI, AICTE and UGC. Oriental University offers various courses across disciplines like Agriculture, Commerce, Computer Applications, Education, Engineering, Law, Library & Information Sciences, Management, Media Studies, Pharmacy, Science etc.",
    "rating": "7.4/10",
    "placements": "7.4/10",
    "courses": "B.Ed , B.A+B.Ed/ , BBA , MBA , B.Tech , M.Ed , BJMC", 
    "exam": "JEE Main",
    "image": "https://oui.edu.in/wp-content/uploads/2022/02/oriental-university-indore-about-us.jpg",
},{
    "id": 9,
    "name": "Shri Govindram Seksaria Institute Of Technology And Science- [SGSITS], Indore",
    "about": "Shri Govindram Seksaria Institute of Technology and Science, Indore was established in 1952. It has been ranked among top 30-40 institutes on national level (including IITs and NITs) by independent bodies. Further, looking at its credentials, All India Council for Technical Education (AICTE) and University Grant Commission (UGC), New Delhi, declared the institute as autonomous in 1989. Under the autonomous state, the institute is affiliated to the Rajiv Gandhi Prodyogiki Vishwavidhyalaya (University of technology of M.P.) Bhopal.",
    "rating": "7.5/10",
    "placements": "7.7/10",
    "courses": "B.E , M.C.A , MBA , M.Tech , MSC , M.Pharm , M.E" , 
    "exam": "MP BE JEE Main",
    "image": "https://images.shiksha.com/mediadata/images/1551439733phpzqmCR0.jpeg",
}
]